### ISSUE TITLE
Not finding custom device

### ISSUE THREAD

**Issue by chasepeeler** [whittedb/udi-av-poly#4]
I have a Sony XBR-65X900H. Everything indicates that it should work. I can invoke SimpleIP commands via netcat on port 20060 just fine.

I've added my device as a custom parameter BRAVIA0001 = 192.168.15.47:20060. It's not showing up in the console, and the logs don't seem to indicate that it is even trying to contact it.

I just deleted the parameter, restarted the server, added it back, and restarted it again. I'm attaching the logs from the point of the second restart request.
[log.txt](https://github.com/whittedb/udi-av-poly/files/5371717/log.txt)

**Comment by whittedb** [comment]
Did you try letting it attempt to auto-detect first?  It looks like the device at 192.168.15.47:20060 is actively refusing the connection.

**Comment by chasepeeler** [comment]
I did. Can I ask where you are seeing that in the log? I don't see anything with 20060 at all.

**Comment by whittedb** [comment]
Yea, I don't see it either.  It's been a couple years since I looked at this code.  I think it's seeing and attempting to connect to a different device.

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.15.54', port=49152): Max retries exceeded with url: /wps_device.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x758700d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
`
Do you have another Sony device on the network?

Either way, I should harden this code to just print an error message and continue on instead of crashing.  Since I only have one Sony device and one Pioneer device I never thought about how to handle multiples where one may not be enabled.

**Comment by chasepeeler** [comment]
Playstation 4 is the only other sony device I can think of. .54 isn't showing up in the device list on my gateway. Grabbing the MAC address from the arp table, it belongs to arris group.

**Comment by whittedb** [comment]
Ahhh, the gateway/router device.  Ok, it doesn't allow insecure web service information requests.  Another thing I didn't think about.  I figured that would always be the case.  I'll make some changes and hopefully be able to push the change tonight.

**Comment by chasepeeler** [comment]
Shouldn't be a gateway/router. My gateway is by Pace, and the AP that it uses for the wireless set top boxes is Cisco. Both of those devices are accounted for. 

I'll update things in the morning if you push out some updates and see how things go.

**Comment by whittedb** [comment]
Updated with bug fix.  If you still have problems, set the log level via the ISY console to Debug or with the Custom Configuration parameter of debugMode = 10.  Restart it and send me the new log that will have more information.

Arris makes cable modems.  I'm almost positive that's what it is since the the SSDP location URL includes /wps_device.xml.  So I'm pretty sure that is whatever wireless AP gizmo you have.  Hard to be positive without knowing your entire setup.

Anyways, let me know how it goes.

**Comment by chasepeeler** [comment]
Okay, compared MAC addresses, and .54 is definitely another interface on my gateway. The only difference between it's MAC address and the one for .54 is the very last character (it's A0, .54 is AB). Which is good, because it means I don't have a rogue cable modem somewhere on my network.

As for the node server. Still not working properly. I decided to fully uninstall it and start over. After it started, I changed the debug level to 10. Stopped it, waited a few minutes, and started it up. I then added a custom parameter for my TV, stopped it, waited a minute, and started it again. I waited between stop and start just give a bit more spacing on the timestamps in the logs.
[newlog.txt](https://github.com/whittedb/udi-av-poly/files/5379603/newlog.txt). Still don't see any indication that it's even attempting the custom configuration item.

A few things that might be easy to add (I'm a programmer myself, but haven't made much progress in figuring out node servers - mainly because I know very little python) and make it easier to see what's happening is configuration parameters to either 1.) exclude IP address from auto discovery or 2.) tell it to skip auto discovery and only use explicitly defined devices in the configuration.

**Comment by whittedb** [comment]
My apologies, I trapped the wrong exception.  I believe I have the right one now.

I thought about option 2, but fixing this bug is the easiest and best, imho, option.  There was another bug and I'm surprised I never noticed it before.  The parameter parsing code wasn't handling BRAVIA devices.  Don't know how I missed adding that to the supported devices list that the parameter parsing uses.

And thank you for your patience and help on getting this straightened out.

**Comment by chasepeeler** [comment]
No problem at all helping out. Like I said, I'm a developer as well. Been doing it 15 years professionally and at least 10 years on top of that if you count school.

Definitely think the fact you weren't parsing out BRAVIA devices would explain the root of the issues I was having :-)

So, I've got your update in place. I went ahead and deleted the node server and re-added it. It doesn't auto discover the TV, but that's fine. I also don't see any uncaught exceptions, so that's good.

When I manually add my TV, it does detect it, and it shows up in the admin console. However, I can't actually do anything after that. I see a lot of "reconnecting" messages in the logs. I'm attaching everything from the point I deleted the previous node server. 
[log3.txt](https://github.com/whittedb/udi-av-poly/files/5386602/log3.txt)

The reconnecting messages started showing up before I even tried to interact with it at all. I also went through and tried all the various buttons and options in the admin console as well. 

Using the documentation here, I've verified that I can interact with my TV using the REST API, IRCC-IP, and Simple IP control
https://pro-bravia.sony.net/develop/integrate/ip-control/index.html. Simple IP control is on port 20600, which is what I specify as the port in the configuration. REST API and IRCC both use port 80. I do have it set up to use a pre-shared key for the REST API and IRCC.

I did not have debugging turned up to 10. Let me know if you want me to change that and get you additional logs.

**Comment by whittedb** [comment]
It's refusing the connection on port 20600 when sending commands.  Shouldn't the port be 20060?

Auto detection won't work since it's looking for a specific model (XBR-65X810C).  I'm not sure if the 900H has extended commands that should be implemented.  Using the custom parameter BRAVIAxxxx causes the code to use the 810C device client.  If there are things you need from the 900H that aren't supported, I might be able to add those.

**Comment by chasepeeler** [comment]
Doh!

It works now. It didn't delete/replace the node - just added a new one, even though I updated the configuration parameter. No big deal, I just deleted the node manually, but wasn't sure if that's an issue or not.

No big deal for me if autodetection works or not. Honestly, I'm not totally sure how much I'll be using it in general. I have a Harmony hub which allows me to do pretty much everything I need to when it comes to the ISY and my TV. I'm sure I'll find something at some point though. 

Glad we were able to get things worked out though!

**Comment by chasepeeler** [comment]
If you ever need me to help out with anything else, just let me know. My email is chasepeeler [at] gmail.com. I can easily switch things to a different branch if needed and I can even do some slight code mods. I know python well enough to mess around with existing code, just not really that great in terms of creating new stuff. I actually want to write a node server for some Eufy devices. There is a Python library out there which does the API communication, I just haven't found a long enough block of time that I can sit down and start playing around with things - since it not only requires getting better at Python, but getting a better idea of the whole polyglot/node server framework - and it's not that easy to tweak a line of code and then see what that change does - which is how I learn such stuff where the documentation isn't that great.

**Comment by whittedb** [comment]
Awesome, thanks for your patience.

Deleting the leftover node is the only way to get rid of the old one.  That's sort of a feature.  If your device uses DNS and it's IP changes, a new device is created and the old one is left intact so you can do a Find/Replace in ISY to update your programs.  Ideally, it shouldn't change anything at all on the ISY side, but I couldn't come up with any other way to create a unique node address other than using the IP/Port of the device.

If you have some time and want to test the auto-detection using the dev branch, that would save me some time having to set up a separate raspberry pi and polyglot for that (something I need to do again but haven't had time for).  Be sure to delete the existing node from polyglot first.

**Comment by chasepeeler** [comment]
That makes sense with the leftover node. 

I'll give the dev branch a try in the next day or two.
